### ISSUE TITLE
Conversions are tracked all as affiliates?

### ISSUE THREAD

**Issue by masiorama** [PrestaShop/ps_googleanalytics#31]
Hello, there, I just noticed a strange behavior in the way the plugin handles the conversions: all the conversions are correctly tracked, but all as affilates, and not as campaign, coupon and so on.
In details, the affiliate is tracked with the name of my website.
Is it expected?
Anybody else noticed this behavior?
Thanks in advance.

**Comment by masiorama** [comment]
No one has the same problem? Any suggestion?

**Comment by masiorama** [comment]
No feedback at all? Is this repository active?

**Comment by gaelgerard** [comment]
What do you mean by affiliates?

**Comment by masiorama** [comment]
@gaelgerard Hello, if you navigate Google Analytics, and go to _Conversions->Ecommerce_ on the overall page you can see all the convertions under the _Marketing_ section, divided into something like _Campains, Internal promotions, Coupon and Affiliations_... Sorry, maybe these are not the exact namings, since I've got the interface in my home language....

**Comment by gaelgerard** [comment]
Ok i didn't see because Enhanced ecommerce wasn't activated on the account I was checking.

It seems it is the same problem I encountered a few days ago while upgrading from PS 1.5 to 1.7

Please go to the Aquisition section and check which channel is bringing transactions? For me it was falsed by payment gateways which were designated as the source of all transactions as referal instead of organic or paid search.

So I followed this https://www.monsterinsights.com/how-to-add-paypal-to-referral-exclusion-list-in-google-analytics/ and now transactions are assigned to the good referrer (organic or paid search).

Since I activated Enhanced ecommerce this morning I can see most of conversions are tracked as affiliates for the last days but I can also see a few ones in Campaings which for me means it was linked with the referral problem too.

This problem occured to me since I upgraded from 1.5 to 1.7 with the official GA module so I think there must be a misconfiguration in the module because I didn't face the same issue on the previous version.

**Comment by masiorama** [comment]
Thank you very much, I will dig into it.

**Comment by matks** [comment]
I guess no more activity since 2019 means the topic is closed. Feel free to reopen a new one if needed.
