### ISSUE TITLE
Pageviews are sent from backoffice (3 times!!!)

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/ps_googleanalytics#64]
New version 4.0.0 is sending pageviews from the backoffice.
What's more wrong, it does _ga('send', 'pageview');_ 3 times.

This influences statistics and should be fixed asap.

**Comment by matks** [comment]
@Hlavtox I have checked the behavior. I can acknowledge the GA event "pageview" is fired twice on BO pages because of a bug.

The PR will fix this https://github.com/PrestaShop/ps_googleanalytics/pull/67

However I do not see 3 events being fired. Can you provide a detailed scenario of how you have setup your shop and module to see that ? I cant see how you could get 3 events.

**Comment by Hlavtox** [comment]
@matks Open BO order view page in 1.7.6.

The bug is present in 1.7.7 also, but you must fix echo to return in hookDisplayAdminOrder in the module.

**Comment by Hlavtox** [comment]
![Výstřižek](https://user-images.githubusercontent.com/6097524/91446618-f22cdc80-e877-11ea-878d-3a9f4113e1b5.PNG)

**Comment by Hlavtox** [comment]
![1](https://user-images.githubusercontent.com/6097524/91448605-5f417180-e87a-11ea-83e9-72d611c0ef5a.PNG)

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/ps_googleanalytics/pull/77

**Comment by matks** [comment]
Fix finally available in new module version https://github.com/PrestaShop/ps_googleanalytics/releases/tag/v4.1.0
