### ISSUE TITLE
help !  Uncaught ReferenceError: GoogleAnalyticEnhancedECommerce is not defined

### ISSUE THREAD

**Issue by WWangYu** [PrestaShop/ps_googleanalytics#87]
I installed the ps_googleanalytics module in prestashop, but it does not take effect. I see in the browser console that “GoogleAnalyticEnhancedECommerce is not defined.”
I tried to reinstall, but it did not solve the problem. Can you tell me what to do. I re-built the prestashop environment locally and did not reproduce this problem.

prestashop version： v1.7.7
ps_googleanalytics version : v4.0
php version : 7.2.24

![捕获](https://user-images.githubusercontent.com/12976264/104267714-258da200-54cd-11eb-8a12-f96e1111ac34.PNG)

**Comment by WWangYu** [comment]
@matks   Hi , please help me

**Comment by rmilecki** [comment]
`GoogleAnalyticEnhancedECommerce` is global object created by JavaScript code in the `GoogleAnalyticActionLib.js`. It's a wrapper (helper) around the "Enhanced Ecommerce" plugin of Googly Analytics.

Since you are getting "GoogleAnalyticEnhancedECommerce is not defined" error, it means that `GoogleAnalyticActionLib.js` was not loaded.

Please check:
1. If your page source contains code **like**
`<script type="text/javascript" src="(...)/GoogleAnalyticActionLib.js" ></script>`
2. If your browser has loaded above file (check the "Network" tab)
Maybe you have some ads blocked installed?
![blocked](https://user-images.githubusercontent.com/452972/107823445-188bf900-6d80-11eb-9b40-c887b28204f5.png)

**Comment by matks** [comment]
Thanks for the answer @rmilecki I close the issue because the answer cannot be improved :)
